### ISSUE TITLE
Users Back-End Routes

### ISSUE THREAD

**Issue by JesseBarron** [ThethreeMuscoders/gamepackig#2]
As a user admin, I would like to get a list of users or a specific user in order to delete or promote a user.

In order to make those requests possible we're going to need the following back-end routes.

- [x] GET '/' - gets all users from the database.
- [x] POST '/' - posts a new user to the database.
- [x] GET '/:userId' - gets a single user by userId.
- [x] DELETE '/:userId' - deletes user with userId.
- [x] PUT '/:userId' - updates user with userId.

**Comment by JesseBarron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Product Model](https://trello.com/c/voDan054/3-product-model)

**Comment by Username2134987** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users Back-End Routes](https://trello.com/c/3pICNctO/12-users-back-end-routes)
